from tkinter import*
c=Tk()
one=Button(c,text="1",fg="blue")
#one.pack(side=LEFT)
one.grid(row=0,column=1)
two=Button(c,text="2",fg="blue")
#two.pack
two.grid(row=0,column=2)
three=Button(c,text="3",fg="blue")
#three.pack
three.grid(row=0,column=3)
four=Button(c,text="4",fg="blue")
#four.pack
four.grid(row=1,column=1)
five=Button(c,text="5",fg="blue")
#five.pack
five.grid(row=1,column=2)
six=Button(c,text="6",fg="blue")
#six.pack
six.grid(row=1,column=3)
seven=Button(c,text="7",fg="blue")
#seven.pack
seven.grid(row=2,column=1)
eight=Button(c,text="8",fg="blue")
#eight.pack
eight.grid(row=2,column=2)
nine=Button(c,text="9",fg="blue")
#nine.pack
nine.grid(row=2,column=3)
zero=Button(c,text="0",fg="blue")
#zero.pack
zero.grid(row=3,column=2)
plus=Button(c,text="+",fg="blue")
plus.grid(row=0,column=4)
minus=Button(c,text="-",fg="blue")
minus.grid(row=1,column=4)
mul=Button(c,text="*",fg="blue")
mul.grid(row=2,column=4)
div=Button(c,text="/",fg="blue")
div.grid(row=3,column=5)
equal=Button(c,text="=",fg="blue")
equal.grid(row=3,column=3)
clear=Button(c,text="CE",fg="blue")
clear.grid(row=0,column=5)
mod=Button(c,text="%",fg="blue")
mod.grid(row=1,column=5)
sq=Button(c,text="sq",fg="blue")
sq.grid(row=3,column=1)
rat=Button(c,text="1/x",fg="blue")
rat.grid(row=2,column=5)
cross=Button(c,text="x",fg="blue")
cross.grid(row=3,column=4)
c.mainloop()
           
         
